name: PR Release Comment

on:
  push:
    tags:
      - '*'

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Comment on PRs
      uses: actions/github-script@v4
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const commentOnPRs = require('./prReleaseComment');
          commentOnPRs(github, context);
